# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# 1) Python telepítése
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# 2) hello.py futtatása
- script: |
    python hello.py
  displayName: 'Run hello.py'

